# Generated by Django 4.2.5 on 2023-09-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_username', models.CharField(max_length=50)),
                ('doctor_name', models.CharField(max_length=60)),
                ('doctor_speciality', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('doctor_fee', models.IntegerField()),
                ('doctor_image', models.ImageField(upload_to='user/images')),
            ],
        ),
    ]
